name: Run tests and build docker image

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Setup python
      uses: actions/setup-python@v2
      with:
        python-version: '3.6'
    
    - name: Install Dependencies
      run: pip install -r requirements.txt -r requirements-test.txt

    - name: Execute tests
      run: python -m unittest discover -s tests/

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: lburinov73/search_engine_crawler:latest
