name: Run tests and build docker image

on: workflow_dispatch

defaults:
  run:
    working-directory: ./src

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Install Dependencies
      run: pip3 install -r requirements.txt -r requirements-test.txt

    - name: Execute tests
      run: python3 -m unittest discover -s tests/

