name: Run tests and build docker image

on: workflow_dispatch

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Check Out Repo 
      uses: actions/checkout@v2

    - name: Install Dependencies
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
      run: pip install -r requirements.txt -r requirements-test.txt

    - name: Execute tests
    - uses: actions/setup-python@v2
      with:
        python-version: '3.6'
      run: python -m unittest discover -s tests/

